### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by bnotg** [axipo/mini-status#2]
执行 `mini-status -a A.B.C.D:8080 -u /status -p 123 `命令的时候，出错
报错信息如下：
```
/usr/lib/node_modules/mini-status/index.js:27
            systemInfoCached.getNetworkTransfer().rx / 1024 ** 2, // MB
                                                             ^

SyntaxError: Unexpected token *
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/mini-status/bin/mini-status-cli.js:3:19)```

**Comment by axipo** [comment]
node 版本是？
运行系统是？

另外，多问一句，虽然觉得不大可能，应该不会一模一样运行了`mini-status -a A.B.C.D:8080 -u /status -p 123`这句吧，A.B.C.D是一个例子，比如 0.0.0.0

**Comment by xqin** [comment]
@bnotg  应该是你node的版本太低了.

`**` 这个操作符, 需要node 版本 `>=7.0`, 7 以前的版本是不支持这个操作符的.

https://node.green/#ES2016-features-exponentiation------operator

**Comment by bnotg** [comment]
> @bnotg 应该是你node的版本太低了.
> 
> `**` 这个操作符, 需要node 版本 `>=7.0`, 7 以前的版本是不支持这个操作符的.
> 
> https://node.green/#ES2016-features-exponentiation------operator

是的，更新node 版本就解决了，THX
