### ISSUE TITLE
出错 

### ISSUE THREAD

**Issue by vvrf** [axipo/mini-status#4]
```
app listen at 0.0.0.0:12345/update
/usr/local/lib/node_modules/mini-status/lib/metrics-utils/networkInfo.js:102
        'rx':(tailCount.rx - headCount.rx) / realDuration,
                        ^

TypeError: Cannot read property 'rx' of undefined
    at getNetworkSpeed (/usr/local/lib/node_modules/mini-status/lib/metrics-utils/networkInfo.js:102:25)
    at getNetworkSpeed (/usr/local/lib/node_modules/mini-status/lib/metrics-utils/systemInfo.js:25:28)
    at Timeout.setTimeout [as _onTimeout] (/usr/local/lib/node_modules/mini-status/lib/metrics-utils/getCacheFunc.js:31:33)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
```

**Comment by axipo** [comment]
node 版本？
系统版本 ？

大致描述下怎么安装的，我好复现看看

**Comment by vvrf** [comment]
```
root@vultr:~# uname -a
Linux vultr.guest 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
root@vultr:~# npm -v
3.5.2
```
```
1. apt-get install npm
2.npm install mini-status -g
3.mini-status -a 0.0.0.0:12345 -p xxxxx
然后就出现那个错误了。。。。。
```
大佬要不要考虑搞个docker，一把唆：）

**Comment by DDCHlsq** [comment]
> node 版本？
> 系统版本 ？
> 
> 大致描述下怎么安装的，我好复现看看

我的阿里云上海有同样的问题
node v13.11.0 with npm v6.13.7
报错
> /usr/local/lib/node_modules/mini-status/lib/metrics-utils/networkInfo.js:102
>        'rx':(tailCount.rx - headCount.rx) / realDuration,
>                       ^
>
>TypeError: Cannot read property 'rx' of undefined
>    at getNetworkSpeed (/usr/local/lib/node_modules/mini-status/lib/metrics->utils/networkInfo
>    at getNetworkSpeed (/usr/local/lib/node_modules/mini-status/lib/metrics->utils/systemInfo.
>    at Timeout._onTimeout (/usr/local/lib/node_modules/mini-status/lib/metrics->utils/getCache
>    at listOnTimeout (internal/timers.js:549:17)
>    at processTimers (internal/timers.js:492:7)

**Comment by axipo** [comment]
@DDCHlsq  @vvrf  看了下，猜测是[这一行](https://github.com/axipo/mini-status/blob/b80fe402dab11cfa4147436cb3c0549a5bb498e0/lib/metrics-utils/networkInfo.js#L30)没有匹配到，麻烦说一下具体系统版本。另外麻烦打印下`cat /proc/net/dev`的结果看看

**Comment by vvrf** [comment]
```
root@vultr:~# cat /proc/net/dev
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
    lo: 5856140   41340    0    0    0     0          0         0  5856140   41340    0    0    0     0       0          0
vethb8b124c: 1031202512   74357    0    0    0     0          0         0  6267715   57438    0    0    0     0       0          0
  ens7:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
docker0: 2550712151 2698441    0    0    0     0          0         0 3896699202 3038651    0    0    0     0       0          0
  ens3: 5320042232 11647629    0    0    0     0          0         0 50711153273 11845630    0    0    0     0       0          0
veth6845670: 44235908   21745    0    0    0     0          0         0  4070334   24947    0    0    0     0       0          0
veth8bed9c9:   15732      36    0    0    0     0          0         0   151134    1547    0    0    0     0       0          0
vethfcb88c7: 383775565  415150    0    0    0     0          0         0 402160052  492874    0    0    0     0       0          0
vetha83db74: 2366264    4750    0    0    0     0          0         0  5962683    4907    0    0    0     0       0          0
veth96131b2: 689735360  961649    0    0    0     0          0         0 701317820  909691    0    0    0     0       0          0
vethf18b845: 407518394  904175    0    0    0     0          0         0 2764070891  766787    0    0    0     0       0          0
vethd25a324: 857654030  902974    0    0    0     0          0         0 870496466  947426    0    0    0     0       0          0

root@vultr:~# cat /proc/version
Linux version 4.15.0-96-generic (buildd@lgw01-amd64-004) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020
```
